### ISSUE TITLE
"Cannot find module 'http-status' or its corresponding type declarations." after migrating to 2.0.0

### ISSUE THREAD

**Issue by dschuessler** [adaltas/node-http-status#53]
**Describe the bug**

After upgrading to `http-status` 2.0.0, I get the following error on every import of the package.

```
src/controllers/metrics.controller.ts:2:24 – error TS2307: Cannot find module 'http-status' or its corresponding type declarations.

2 import httpStatus from 'http-status';
                         ~~~~~~~~~~~~~
```

**To Reproduce**

1. Clone https://github.com/dschuessler/http-status-import-bug
2. Run `npm run build`

**Additional context**

I consider this a bug since the README claims that, for ESM users, the import remains the same.

**Comment by gregorio-gerardi** [comment]
same here

**Comment by wdavidw** [comment]
It seems like you are using TypeScript. The repo [http-status-import-bug](https://github.com/dschuessler/http-status-import-bug) provided above is configured for CommonJS. 

- no "type" field set to "module" in the package.json file, add
  ```json
  {
    "type": "module"
  }
  ```
- "module" field set to "commonjs" in the tsconfig.json, replace with
  ```js
  {
    "compilerOptions": {
      "target": "esnext",
      "module": "NodeNext",
      "moduleResolution": "NodeNext",
   }
  }
  ```

**Comment by wouterds** [comment]
You can import it from `/dist`, so changing
```ts
import httpStatus from 'http-status';
```

to
```ts
import httpStatus from 'http-status/dist';
```

Will work, but ideally it would indeed just keep working as it was.

**Comment by wdavidw** [comment]
Please share your envionnement (Browser/Node.js, CommonJS/ESM, JS/TS, ...). For example, there shouldn't be a need to import `/dist` with Node.js.

**Comment by wouterds** [comment]
I'll look into a repro this evening, but TLDR I can't get it to work with CommonJS without importing from the /dist sub-folder.

**Comment by wdavidw** [comment]
With Node.js and without TypeScript ?

**Comment by wouterds** [comment]
Node.js 20, compiled with tsc from TS to JS
```json
{
  "lib": ["ESNext"],
  "module": "CommonJS",
  "moduleResolution": "Node",
  "target": "ESNext",
}
```

**Comment by wouterds** [comment]
Here's a reproducible example, you'll notice that `npm run build` will fail with

```
> http-status-repro@0.1.0 build
> tsc

src/index.ts:1:24 - error TS2307: Cannot find module 'http-status' or its corresponding type declarations.
  There are types at '/Users/wouterds/Projects/http-status-repro/node_modules/http-status/dist/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

1 import httpStatus from "http-status";
                         ~~~~~~~~~~~~~


Found 1 error in src/index.ts:1
```

While if you downgrade `http-status` to `1.8.1`, or change the import to `import httpStatus from "http-status/dist";`, it will work.
